name: Auto-Fix Code Styling

on:
  pull_request:
    branches:
      - "**"  # Runs on PRs to any branch

jobs:
  codestyle:
    name: Check and Fix Code Styling
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  
      - name: Install composer dependencies
        run: |
          composer install -o -q
  
      - name: Install npm dependencies
        run: |
          composer fix-cs

      - name: Commit and push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }} # Push changes back to the PR branch
          force: true
  
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              body: "Code styling issues have been fixed and committed to the PR branch automatically."
            })
